package view.employee;

import java.awt.Label;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import main.FYSApp;
import view.LoginScreen;

/**
 *
 * @author Team 1 IS106 ZoekJeKoffer
 */
public class EmployeeFront extends JPanel {

    /**
     * Creates new form EmployeeFront
     */
    public EmployeeFront() {
        initComponents();
        setLoggedInAs();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        foundJButton = new javax.swing.JButton();
        lostJButton = new javax.swing.JButton();
        logoutJButton = new javax.swing.JButton();
        loggedInAs = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 102, 102));
        setToolTipText("");
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        foundJButton.setBackground(new java.awt.Color(255, 255, 255));
        foundJButton.setText("FOUND");
        foundJButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        foundJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                foundJButtonMouseClicked(evt);
            }
        });
        foundJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foundJButtonActionPerformed(evt);
            }
        });
        add(foundJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 170, 130));

        lostJButton.setBackground(new java.awt.Color(255, 255, 255));
        lostJButton.setText("LOST");
        lostJButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lostJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lostJButtonActionPerformed(evt);
            }
        });
        add(lostJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, 170, 130));

        logoutJButton.setText("Logout");
        logoutJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutJButtonActionPerformed(evt);
            }
        });
        add(logoutJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 20, 90, 30));

        loggedInAs.setForeground(new java.awt.Color(255, 255, 255));
        loggedInAs.setText("[username]");
        add(loggedInAs, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 20, -1, -1));
        loggedInAs.getAccessibleContext().setAccessibleName("lbl_currently");
        loggedInAs.getAccessibleContext().setAccessibleDescription("");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Currently logged in as:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Corendon-background.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void foundJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foundJButtonActionPerformed

        FYSApp.getInstance().showPanel(new FoundLuggageOverview());
    }//GEN-LAST:event_foundJButtonActionPerformed

    private void lostJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lostJButtonActionPerformed

    
        try {
            FYSApp.getInstance().showPanel(new LostLuggageOverview());
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(EmployeeFront.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
    }//GEN-LAST:event_lostJButtonActionPerformed

    private void logoutJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutJButtonActionPerformed
        FYSApp.getInstance().showPanel(new LoginScreen());
    }//GEN-LAST:event_logoutJButtonActionPerformed

    private void foundJButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_foundJButtonMouseClicked
        FYSApp.getInstance().showPanel(new FoundLuggageOverview());
         
    }//GEN-LAST:event_foundJButtonMouseClicked


    private void setLoggedInAs(){
        String userName = FYSApp.getQueryManager().getUserName();
        System.out.println(userName);
        loggedInAs.setText(userName);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton foundJButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel loggedInAs;
    private javax.swing.JButton logoutJButton;
    private javax.swing.JButton lostJButton;
    // End of variables declaration//GEN-END:variables
}
