/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.employee;

import QueryManager.DatabaseManager;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import main.FYSApp;
import main.Frame;
import model.Client;
import model.Luggage;

/**
 *
 * @author Lars
 */
public class MatchingLuggage extends JPanel {

    // Always declare first..!
    DatabaseManager dbmanager = new DatabaseManager();
    Connection conn = null;
    private static ResultSet rs = null;
    PreparedStatement pst = null;
    private String input;
    private static ResultSetMetaData rsmetadata;
    private static int columns = 0;
    private static final int UPDATE_MODE_FALSE = 0;
    private int WHICH_STATUS = 0;
    private boolean lost;
    private static String brand;
    private static String lableCode;
    private static String material;
    private static String otherDetails;
    private static String color;
    private static String departureFrom;
    private static String weightClass;
    private static String firstName;
    private static String middleName;
    private static String lastName;
    private static String phoneNumber;
    private static String email;
    private static String country;
    private static String address;
    private static String city;
    private static String state;
    private static String zipCode;
    private static String whenFound;
    private static String foundAt;
    private static int updateMode = 0;
    private static int luggageid;
    private static int clientid;
    private static String lostOrFound = "";

    /**
     * Creates new form Match
     */
    public MatchingLuggage() {
        initComponents();

        setLoggedInAs();
    }

    public static void setLostOrFound(String lostOrFound) {
        MatchingLuggage.lostOrFound = lostOrFound;
    }

    public static void setTextLuggage(Luggage luggage) {
        brand = luggage.getBrand();
        lableCode = luggage.getLableCode();
        material = luggage.getMaterial();
        otherDetails = luggage.getOtherDetails();
        color = luggage.getColor();
        departureFrom = luggage.getDepartureFrom();
        weightClass = luggage.getWeightClass();
        whenFound = luggage.getWhenFound();
        foundAt = luggage.getFoundAt();

    }

    //Bij Lost koffers nodig

    public static void setTextClient(Client client) {
        firstName = client.getFirstName();
        middleName = client.getMiddleName();
        lastName = client.getLastName();
        phoneNumber = client.getPhone();
        email = client.getEmail();
        country = client.getCountry();
        address = client.getAddress();
        city = client.getCity();
        state = client.getState();
        zipCode = client.getZipCode();
    }

    /**
     * Creates new form RegisterSolvesLuggage
     *
     * @param id
     */
    public static void setUpdate(int id) {
        updateMode = id;
        luggageid = id;
        clientid = id;
    }

    /**
     * Matched luggage
     *
     * @param resultSet
     */
    public static void getMatchingLuggage(ResultSet resultSet) {
        MatchingLuggage.rs = resultSet;
        try {
            updateTable(rs);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(MatchingLuggage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * Creates new form ML
     */
    private static void updateTable(ResultSet rs) throws ClassNotFoundException, SQLException {

        rsmetadata = rs.getMetaData();

        columns = rsmetadata.getColumnCount();

        DefaultTableModel dtm = new DefaultTableModel();

        Vector columns_name = new Vector();
        Vector data_rows = new Vector();

        for (int i = 1; i < columns; i++) {
            columns_name.addElement(rsmetadata.getColumnName(i));
        }
        dtm.setColumnIdentifiers(columns_name);

        while (rs.next()) {

            data_rows = new Vector();

            for (int j = 1; j < columns; j++) {
                data_rows.addElement(rs.getString(j));
            }
            dtm.addRow(data_rows);
        }

        matchingLuggageTable.setModel(dtm);

        matchingLuggageTable.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        matchingLuggageTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        registerJButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        logoutJButton = new javax.swing.JButton();
        matchJButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        loggedInAs = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        matchingLuggageTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        matchingLuggageTable.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        matchingLuggageTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "LuggageID", "Status", "ownerID", "Airport", "Brand", "LableCode", "Material", "other details", "weightclass", "Color", "Whenfound", "Found at", "Departurefrom", "Created", "Lastupdated"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(matchingLuggageTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 790, 380));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/match-icon.png"))); // NOI18N
        jLabel5.setText("  Matching Luggage");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 410, 33));

        registerJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add-icon.png"))); // NOI18N
        registerJButton.setText(" REGISTER LUGGAGE");
        registerJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerJButtonActionPerformed(evt);
            }
        });
        add(registerJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 490, 210, 40));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(" Luggage found?");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, 130, 33));

        logoutJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout-icon.png"))); // NOI18N
        logoutJButton.setText("Logout");
        logoutJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutJButtonActionPerformed(evt);
            }
        });
        add(logoutJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(917, 20, -1, 30));

        matchJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/match-icon.png"))); // NOI18N
        matchJButton.setText(" MATCH");
        matchJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matchJButtonActionPerformed(evt);
            }
        });
        add(matchJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 490, 110, 40));

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Luggage not found?");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 460, 170, 33));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Currently logged in as: ");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        loggedInAs.setForeground(new java.awt.Color(255, 255, 255));
        loggedInAs.setText("jLabel2");
        add(loggedInAs, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Corendon-background.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setAutoscrolls(true);
        jLabel3.setMaximumSize(new java.awt.Dimension(1024, 600));
        jLabel3.setMinimumSize(new java.awt.Dimension(1024, 600));
        jLabel3.setPreferredSize(new java.awt.Dimension(1024, 600));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void registerJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerJButtonActionPerformed
        //  Create solved luggage item with user input
        Luggage luggage = new Luggage(brand, lableCode, color,
                otherDetails, lostOrFound, material, weightClass, whenFound, foundAt,
                departureFrom);

        // Create solved client item with user input
        Client client = new Client(firstName, middleName, lastName, phoneNumber,
                email, country, address, city, state, zipCode);

//        FYSApp.getLuggageManager().updateLuggage(luggage, luggageid);
//        FYSApp.getClientManager().updateClient(client, clientid);
        FYSApp.getClientManager().addClient(client);
        int id = FYSApp.getClientManager().getClientid();
        FYSApp.getLuggageManager().addLostLuggage(luggage, id);
        if (lostOrFound.equalsIgnoreCase("found")) {
            Frame.getInstance().showPanel(new FoundLuggageOverview());
        } else {
            try {
                Frame.getInstance().showPanel(new LostLuggageOverview());
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(MatchingLuggage.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        JOptionPane.showMessageDialog(null, "Information is saved");
    }//GEN-LAST:event_registerJButtonActionPerformed

    private void logoutJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutJButtonActionPerformed
        Frame.shutdown();
        FYSApp.logout();
    }//GEN-LAST:event_logoutJButtonActionPerformed

    private void matchJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matchJButtonActionPerformed

        if (matchingLuggageTable.getSelectedRow() >= 0) {
            int row = matchingLuggageTable.getSelectedRow();
            int col = 0;
            int id = Integer.parseInt((String) matchingLuggageTable.getModel().getValueAt(row, col));
            Luggage luggage = FYSApp.getLuggageManager().getSelectedLuggage(id);
            Client client = FYSApp.getClientManager().getSelectedClient(id);
            Frame.getInstance().showPanel(new RegisterSolvesLuggage());
            RegisterSolvesLuggage.setUpdate(id);
            RegisterSolvesLuggage.setTextLuggage(luggage);
            RegisterSolvesLuggage.setTextClient(client);
        } else {
            JOptionPane.showMessageDialog(null,
                    "Please select a row!",
                    "Error",
                    JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_matchJButtonActionPerformed

    private void setLoggedInAs() {
        String userName = FYSApp.getUserManager().getUserName();
        loggedInAs.setText(userName);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel loggedInAs;
    private javax.swing.JButton logoutJButton;
    private javax.swing.JButton matchJButton;
    private static javax.swing.JTable matchingLuggageTable;
    private javax.swing.JButton registerJButton;
    // End of variables declaration//GEN-END:variables

}
