/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.employee;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import main.FYSApp;
import main.Frame;
import model.Luggage;
import model.Client;
import view.admin.AdminLuggageFound;

/**
 *
 * @author Lars
 */
public class RegisterSolvesLuggage extends javax.swing.JPanel {

    private static int updateMode = 0;
    private static int luggageid;
    private static int clientid;
    
    /**
     * Creates new form RegisterSolvesLuggage
     * @param luggage
     */
    public static void setTextLuggage(Luggage luggage) {
        txt_brand.setText(luggage.getBrand());
        txt_lableCode.setText(luggage.getLableCode());
        txt_material.setText(luggage.getMaterial());
        txt_otherDetails.setText(luggage.getOtherDetails());
        cmb_color.setSelectedItem(luggage.getColor());
        cmb_departureFrom.setSelectedItem(luggage.getDepartureFrom());
        cmb_weightClass.setSelectedItem(luggage.getWeightClass());
       }
    public static void setTextClient(Client client) {
        txt_firstName.setText(client.getFirstName());
        txt_middleName.setText(client.getMiddleName());
        txt_lastName.setText(client.getLastName());
        txt_phoneNumber.setText(client.getPhone());
        txt_email.setText(client.getEmail());
        txt_country.setText(client.getCountry());
        txt_address.setText(client.getAddress());
        txt_city.setText(client.getCity());
        txt_state.setText(client.getState());
        txt_zipCode.setText(client.getZipCode());  
    }
        
    /**
     * Creates new form RegisterSolvesLuggage
     * @param id
     */
    public static void setUpdate(int id) {
        updateMode = id;
        luggageid = id;
        clientid = id;
    }
    
    /**
     * Creates new form RegisterSolvesLuggage
     */
    public RegisterSolvesLuggage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_brand = new javax.swing.JLabel();
        lbl_color = new javax.swing.JLabel();
        lbl_weightClass = new javax.swing.JLabel();
        lbl_foundAt = new javax.swing.JLabel();
        lbl_code = new javax.swing.JLabel();
        lbl_material = new javax.swing.JLabel();
        txt_whenFound = new javax.swing.JTextField();
        txt_material = new javax.swing.JTextField();
        txt_lableCode = new javax.swing.JTextField();
        cmb_foundAt = new javax.swing.JComboBox();
        cmb_weightClass = new javax.swing.JComboBox();
        cmb_color = new javax.swing.JComboBox();
        txt_brand = new javax.swing.JTextField();
        btn_submit = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        logoutJButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbl_firstname = new javax.swing.JLabel();
        txt_firstName = new javax.swing.JTextField();
        txt_middleName = new javax.swing.JTextField();
        lbl_middlename = new javax.swing.JLabel();
        lbl_lastname = new javax.swing.JLabel();
        txt_lastName = new javax.swing.JTextField();
        txt_phoneNumber = new javax.swing.JTextField();
        lbl_phoneNumber = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        lbl_country = new javax.swing.JLabel();
        txt_country = new javax.swing.JTextField();
        lbl_address = new javax.swing.JLabel();
        txt_address = new javax.swing.JTextField();
        lbl_city = new javax.swing.JLabel();
        txt_city = new javax.swing.JTextField();
        lbl_state = new javax.swing.JLabel();
        txt_state = new javax.swing.JTextField();
        lbl_zipCode = new javax.swing.JLabel();
        txt_zipCode = new javax.swing.JTextField();
        lbl_whenFound1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_otherDetails = new javax.swing.JTextArea();
        lbl_otherDetails1 = new javax.swing.JLabel();
        cmb_departureFrom = new javax.swing.JComboBox();
        lbl_departureFrom = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_brand.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lbl_brand.setForeground(new java.awt.Color(255, 255, 255));
        lbl_brand.setText("Brand:");
        add(lbl_brand, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, -1));

        lbl_color.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lbl_color.setForeground(new java.awt.Color(255, 255, 255));
        lbl_color.setText("Color:");
        add(lbl_color, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        lbl_weightClass.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lbl_weightClass.setForeground(new java.awt.Color(255, 255, 255));
        lbl_weightClass.setText("Weight class:");
        add(lbl_weightClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));

        lbl_foundAt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lbl_foundAt.setForeground(new java.awt.Color(255, 255, 255));
        lbl_foundAt.setText("Found at");
        add(lbl_foundAt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        lbl_code.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lbl_code.setForeground(new java.awt.Color(255, 255, 255));
        lbl_code.setText("lable code");
        add(lbl_code, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        lbl_material.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lbl_material.setForeground(new java.awt.Color(255, 255, 255));
        lbl_material.setText("Material:");
        add(lbl_material, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, -1, -1));

        txt_whenFound.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txt_whenFound.setText("dd-MM-yyyy");
        txt_whenFound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_whenFoundActionPerformed(evt);
            }
        });
        add(txt_whenFound, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 160, -1));

        txt_material.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txt_material.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_materialActionPerformed(evt);
            }
        });
        add(txt_material, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 160, 20));

        txt_lableCode.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txt_lableCode.setText("0000-2222-3333");
        txt_lableCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_lableCodeActionPerformed(evt);
            }
        });
        add(txt_lableCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 160, 20));

        cmb_foundAt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmb_foundAt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_foundAtActionPerformed(evt);
            }
        });
        add(cmb_foundAt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 160, -1));

        cmb_weightClass.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmb_weightClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_weightClassActionPerformed(evt);
            }
        });
        add(cmb_weightClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 160, -1));

        cmb_color.setMaximumRowCount(15);
        cmb_color.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"red", "green", "yellow", "gray"}));
        cmb_color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_colorActionPerformed(evt);
            }
        });
        add(cmb_color, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 160, -1));

        txt_brand.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txt_brand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_brandActionPerformed(evt);
            }
        });
        add(txt_brand, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 160, -1));

        btn_submit.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btn_submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/match-icon.png"))); // NOI18N
        btn_submit.setText("SOLVE LUGGAGE");
        btn_submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_submitMouseClicked(evt);
            }
        });
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });
        add(btn_submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 490, 160, 30));

        backJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Back-2-2-icon.png"))); // NOI18N
        backJButton.setText(" BACK");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 70, 100, 30));

        logoutJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout-icon.png"))); // NOI18N
        logoutJButton1.setText("Logout");
        logoutJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutJButton1ActionPerformed(evt);
            }
        });
        add(logoutJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 10, 110, 40));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/users-icon.png"))); // NOI18N
        jLabel5.setText("  Owner");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 50, 200, 33));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Currently logged in as: [username]");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, -1, -1));

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/match-icon.png"))); // NOI18N
        jLabel6.setText("  Register Solved Luggage");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 410, 33));

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/found-luggage-icon.png"))); // NOI18N
        jLabel7.setText("  Luggage");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 200, 33));

        lbl_firstname.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lbl_firstname.setForeground(new java.awt.Color(255, 255, 255));
        lbl_firstname.setText("Firstname");
        add(lbl_firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, -1, -1));

        txt_firstName.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txt_firstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_firstNameActionPerformed(evt);
            }
        });
        add(txt_firstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 100, 190, -1));

        txt_middleName.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txt_middleName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_middleNameActionPerformed(evt);
            }
        });
        add(txt_middleName, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 130, 190, -1));

        lbl_middlename.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lbl_middlename.setForeground(new java.awt.Color(255, 255, 255));
        lbl_middlename.setText("Middlename");
        add(lbl_middlename, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, -1, -1));

        lbl_lastname.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lbl_lastname.setForeground(new java.awt.Color(255, 255, 255));
        lbl_lastname.setText("Lastname");
        add(lbl_lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, -1, -1));

        txt_lastName.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txt_lastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_lastNameActionPerformed(evt);
            }
        });
        add(txt_lastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 160, 190, -1));

        txt_phoneNumber.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txt_phoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_phoneNumberActionPerformed(evt);
            }
        });
        add(txt_phoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 200, 190, -1));

        lbl_phoneNumber.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lbl_phoneNumber.setForeground(new java.awt.Color(255, 255, 255));
        lbl_phoneNumber.setText("Phonenumber");
        add(lbl_phoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, -1, -1));

        lbl_email.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lbl_email.setForeground(new java.awt.Color(255, 255, 255));
        lbl_email.setText("Email");
        add(lbl_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, -1, -1));

        txt_email.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });
        add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 230, 190, -1));

        lbl_country.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lbl_country.setForeground(new java.awt.Color(255, 255, 255));
        lbl_country.setText("Country ");
        add(lbl_country, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, -1, -1));

        txt_country.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txt_country.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_countryActionPerformed(evt);
            }
        });
        add(txt_country, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 270, 190, -1));

        lbl_address.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lbl_address.setForeground(new java.awt.Color(255, 255, 255));
        lbl_address.setText("Address");
        add(lbl_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, -1, -1));

        txt_address.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txt_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_addressActionPerformed(evt);
            }
        });
        add(txt_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 300, 190, -1));

        lbl_city.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lbl_city.setForeground(new java.awt.Color(255, 255, 255));
        lbl_city.setText("City");
        add(lbl_city, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, -1, -1));

        txt_city.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txt_city.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cityActionPerformed(evt);
            }
        });
        add(txt_city, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 330, 190, -1));

        lbl_state.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lbl_state.setForeground(new java.awt.Color(255, 255, 255));
        lbl_state.setText("State");
        add(lbl_state, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 370, -1, -1));

        txt_state.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txt_state.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_stateActionPerformed(evt);
            }
        });
        add(txt_state, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 370, 190, -1));

        lbl_zipCode.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lbl_zipCode.setForeground(new java.awt.Color(255, 255, 255));
        lbl_zipCode.setText("Zipcode");
        add(lbl_zipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 400, -1, -1));

        txt_zipCode.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txt_zipCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_zipCodeActionPerformed(evt);
            }
        });
        add(txt_zipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 400, 110, -1));

        lbl_whenFound1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lbl_whenFound1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_whenFound1.setText("When found:");
        add(lbl_whenFound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, -1, -1));

        txt_otherDetails.setColumns(20);
        txt_otherDetails.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txt_otherDetails.setRows(5);
        jScrollPane2.setViewportView(txt_otherDetails);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 340, 90));

        lbl_otherDetails1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lbl_otherDetails1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_otherDetails1.setText("Other details:");
        add(lbl_otherDetails1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, -1, -1));

        cmb_departureFrom.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmb_departureFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_departureFromActionPerformed(evt);
            }
        });
        add(cmb_departureFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 160, -1));

        lbl_departureFrom.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lbl_departureFrom.setForeground(new java.awt.Color(255, 255, 255));
        lbl_departureFrom.setText("Departure from:");
        add(lbl_departureFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Corendon-background.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txt_whenFoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_whenFoundActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_whenFoundActionPerformed

    private void txt_materialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_materialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_materialActionPerformed

    private void txt_lableCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_lableCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_lableCodeActionPerformed

    private void cmb_foundAtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_foundAtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_foundAtActionPerformed

    private void cmb_weightClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_weightClassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_weightClassActionPerformed

    private void cmb_colorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_colorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_colorActionPerformed

    private void txt_brandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_brandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_brandActionPerformed

    private void btn_submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_submitMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_submitMouseClicked

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed

         //  store user input in variables
        String brand            = txt_brand.getText();
        
        String color
                = String.valueOf(cmb_color.getSelectedItem());
        String weightClass
                = String.valueOf(cmb_weightClass.getSelectedItem());
        String foundAt
                = String.valueOf(cmb_foundAt.getSelectedItem());
        
        String lableCode        = txt_lableCode.getText();
        String material         = txt_material.getText();
        String whenFound        = txt_whenFound.getText();
        String otherDetails     = txt_otherDetails.getText();
        String status           = "Solved";
        
        String departureFrom    = 
                String.valueOf(cmb_departureFrom.getSelectedItem()); 
        
        String firstName         = txt_firstName.getText();
        String middleName        = txt_middleName.getText();
        String lastName          = txt_lastName.getText();
        String phoneNumber       = txt_phoneNumber.getText();
        String email             = txt_email.getText();
        String country           = txt_country.getText();
        String address           = txt_address.getText();
        String city              = txt_city.getText();
        String state             = txt_state.getText();
        String zipCode           = txt_zipCode.getText();
        

        //  Create solved luggage item with user input
        Luggage luggage = new Luggage(brand, lableCode, color,
                otherDetails, status, material, weightClass, whenFound, foundAt,
                departureFrom);

        // Create solved client item with user input
        Client client = new Client(firstName, middleName, lastName, phoneNumber,
                email, country, address, city, state, zipCode);
        
        //Custom button text
        Object[] options = {"Yes",
            "No"};
        int n = JOptionPane.showOptionDialog(null,
                "Are you sure you want to change the status of this luggage to Solved?",
                "Warning",
                JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                options,
                null);
        if (n == JOptionPane.YES_OPTION) {
            FYSApp.getLuggageManager().updateSolvedLuggage(luggage, luggageid);
            FYSApp.getClientManager().updateClient(client, clientid);
//            Frame.getInstance().showPanel(new MatchingLuggage());
        } 
    }//GEN-LAST:event_btn_submitActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        Frame.getInstance().showPanel(new MatchingLuggage());
    }//GEN-LAST:event_backJButtonActionPerformed

    private void logoutJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutJButton1ActionPerformed
        Frame.shutdown();
        FYSApp.logout();
    }//GEN-LAST:event_logoutJButton1ActionPerformed

    private void txt_firstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_firstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_firstNameActionPerformed

    private void txt_middleNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_middleNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_middleNameActionPerformed

    private void txt_lastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_lastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_lastNameActionPerformed

    private void txt_phoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_phoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_phoneNumberActionPerformed

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void txt_countryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_countryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_countryActionPerformed

    private void txt_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_addressActionPerformed

    private void txt_cityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cityActionPerformed

    private void txt_stateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_stateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_stateActionPerformed

    private void txt_zipCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_zipCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_zipCodeActionPerformed

    private void cmb_departureFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_departureFromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_departureFromActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btn_submit;
    private static javax.swing.JComboBox cmb_color;
    private static javax.swing.JComboBox cmb_departureFrom;
    private static javax.swing.JComboBox cmb_foundAt;
    private static javax.swing.JComboBox cmb_weightClass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_address;
    private javax.swing.JLabel lbl_brand;
    private javax.swing.JLabel lbl_city;
    private javax.swing.JLabel lbl_code;
    private javax.swing.JLabel lbl_color;
    private javax.swing.JLabel lbl_country;
    private javax.swing.JLabel lbl_departureFrom;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_firstname;
    private javax.swing.JLabel lbl_foundAt;
    private javax.swing.JLabel lbl_lastname;
    private javax.swing.JLabel lbl_material;
    private javax.swing.JLabel lbl_middlename;
    private javax.swing.JLabel lbl_otherDetails1;
    private javax.swing.JLabel lbl_phoneNumber;
    private javax.swing.JLabel lbl_state;
    private javax.swing.JLabel lbl_weightClass;
    private javax.swing.JLabel lbl_whenFound1;
    private javax.swing.JLabel lbl_zipCode;
    private javax.swing.JButton logoutJButton1;
    private static javax.swing.JTextField txt_address;
    private static javax.swing.JTextField txt_brand;
    private static javax.swing.JTextField txt_city;
    private static javax.swing.JTextField txt_country;
    private static javax.swing.JTextField txt_email;
    private static javax.swing.JTextField txt_firstName;
    private static javax.swing.JTextField txt_lableCode;
    private static javax.swing.JTextField txt_lastName;
    private static javax.swing.JTextField txt_material;
    private static javax.swing.JTextField txt_middleName;
    private static javax.swing.JTextArea txt_otherDetails;
    private static javax.swing.JTextField txt_phoneNumber;
    private static javax.swing.JTextField txt_state;
    private static javax.swing.JTextField txt_whenFound;
    private static javax.swing.JTextField txt_zipCode;
    // End of variables declaration//GEN-END:variables
}
