/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.employee;

import main.FYSApp;
import view.LoginScreen;

/**
 *
 * @author Gebruiker
 */
public class RegisterLostLuggage extends javax.swing.JPanel {

    /**
     * Creates new form RegisterLostLuggage
     */
    public RegisterLostLuggage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        canvas1 = new java.awt.Canvas();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1024, 600));
        setMinimumSize(new java.awt.Dimension(1024, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Register Lost Luggage");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 200, 30));

        jButton1.setText("Log out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, -1, -1));

        jButton2.setText("<- back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 440, -1, -1));

        jTextField1.setText("Label number");
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 150, 180, -1));

        jTextField2.setText("Name passenger");
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 210, -1));

        jTextField3.setText("Email adress passenger");
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 210, -1));

        jTextField4.setText("Phone number passenger");
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 210, -1));

        jTextField5.setText("Airport");
        add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, 210, -1));

        jTextField6.setText("Appearance luggage");
        add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, 210, 70));

        jTextField7.setText("DD/MM/YYYY");
        add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, 210, -1));

        jButton3.setText("Submit");
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, 70, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Corendon-background.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new LoginScreen().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        FYSApp.getInstance().showPanel(new LostLuggageOverview());
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Canvas canvas1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
