package view.employee;

import com.sun.webkit.dom.EventImpl;
import java.awt.Font;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import static jdk.nashorn.internal.runtime.JSType.isNumber;
import main.FYSApp;
import main.Frame;
import model.Client;
import model.Luggage;

/**
 *
 * @author Team 1 IS106 ZoekJeKoffer
 */
public class RegisterLostLuggage extends JPanel {

    private static int updateMode = 0;
    private static int luggageid;

    //private Client client;
    /**
     * Creates new form RegisterLostLuggage
     */
    public RegisterLostLuggage() {

        initComponents();

        //        for (int i = 0; i < airportsList.size(); i++) {
        //            cmb_departureFrom.addItem(airportsList);
        //        }
        //
        //  These items should be stored in an array
        cmb_color.addItem("other..");
        cmb_color.addItem("red");
        cmb_color.addItem("blue");
        cmb_color.addItem("cyan");
        cmb_color.addItem("yellow");
        cmb_color.addItem("pink");
        cmb_color.addItem("magenta");
        cmb_color.addItem("green");
        cmb_color.addItem("black");
        cmb_color.addItem("white");
        cmb_color.addItem("orange");
        cmb_color.addItem("grey");
        cmb_color.addItem("brown");

        cmb_weightClass.addItem("other..");
        cmb_weightClass.addItem("0kg - 5kg");
        cmb_weightClass.addItem("5kg - 10kg");
        cmb_weightClass.addItem("10kg - 15kg");
        cmb_weightClass.addItem("15kg - 20kg");
        cmb_weightClass.addItem("20kg+");
    }

    public static void setUpdate(int id) {
        RegisterLostLuggage.updateMode = id;
        RegisterLostLuggage.luggageid = id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        canvas1 = new java.awt.Canvas();
        jPanel2 = new javax.swing.JPanel();
        backJButton = new javax.swing.JButton();
        logoutJButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lbl_color = new javax.swing.JLabel();
        txt_brand = new javax.swing.JTextField();
        cmb_departureFrom = new javax.swing.JComboBox();
        lbl_departureFrom = new javax.swing.JLabel();
        lbl_material1 = new javax.swing.JLabel();
        txt_material = new javax.swing.JTextField();
        lbl_brand1 = new javax.swing.JLabel();
        lbl_lableCode1 = new javax.swing.JLabel();
        txt_lableCode = new javax.swing.JTextField();
        lbl_weightClass = new javax.swing.JLabel();
        cmb_weightClass = new javax.swing.JComboBox();
        cmb_color = new javax.swing.JComboBox();
        lbl_otherDetails = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txt_otherDetails = new javax.swing.JTextArea();
        lbldefaultvaluemiddlename = new javax.swing.JLabel();
        lbldefaultvalueemail = new javax.swing.JLabel();
        lbldefaultvaluezipcode = new javax.swing.JLabel();
        lbldefaultvaluecode = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btn_clear = new javax.swing.JButton();
        lbl_state = new javax.swing.JLabel();
        lbl_middlename = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        txt_phoneNumber = new javax.swing.JTextField();
        txt_address = new javax.swing.JTextField();
        lbl_lastname = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        lbl_firstname = new javax.swing.JLabel();
        lbl_country = new javax.swing.JLabel();
        lbl_phoneNumber = new javax.swing.JLabel();
        txt_firstname = new javax.swing.JTextField();
        txt_lastName = new javax.swing.JTextField();
        txt_state = new javax.swing.JTextField();
        txt_city = new javax.swing.JTextField();
        txt_zipcode = new javax.swing.JTextField();
        lbl_city = new javax.swing.JLabel();
        lbl_zipCode = new javax.swing.JLabel();
        lbl_address = new javax.swing.JLabel();
        txt_middlename = new javax.swing.JTextField();
        txt_country = new javax.swing.JTextField();
        checkPDF = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        btn_submit1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));
        setMaximumSize(new java.awt.Dimension(1024, 600));
        setMinimumSize(new java.awt.Dimension(1024, 600));

        jPanel2.setBackground(new java.awt.Color(255, 241, 234));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        backJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Back-2-2-icon.png"))); // NOI18N
        backJButton.setText(" ");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        logoutJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout-icon.png"))); // NOI18N
        logoutJButton.setText(" ");
        logoutJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(logoutJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(backJButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoutJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backJButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 241, 234));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbl_color.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_color.setText("Color");

        txt_brand.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_brand.setName("txtBrand"); // NOI18N
        txt_brand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_brandActionPerformed(evt);
            }
        });

        cmb_departureFrom.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmb_departureFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_departureFromActionPerformed(evt);
            }
        });

        lbl_departureFrom.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_departureFrom.setText("Departure from");

        lbl_material1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_material1.setText("Material");

        txt_material.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_material.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_materialActionPerformed(evt);
            }
        });

        lbl_brand1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_brand1.setText("Brand");

        lbl_lableCode1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_lableCode1.setText("Lable Code");

        txt_lableCode.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_lableCode.setText(" ");
        txt_lableCode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_lableCodeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_lableCodeFocusLost(evt);
            }
        });
        txt_lableCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_lableCodeActionPerformed(evt);
            }
        });
        txt_lableCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_lableCodeKeyPressed(evt);
            }
        });

        lbl_weightClass.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_weightClass.setText("Weight class");

        cmb_weightClass.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmb_weightClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_weightClassActionPerformed(evt);
            }
        });

        cmb_color.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmb_color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_colorActionPerformed(evt);
            }
        });

        lbl_otherDetails.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_otherDetails.setText("Other details");

        txt_otherDetails.setColumns(20);
        txt_otherDetails.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_otherDetails.setRows(5);
        jScrollPane4.setViewportView(txt_otherDetails);

        lbldefaultvaluemiddlename.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbldefaultvaluemiddlename.setForeground(new java.awt.Color(204, 204, 204));
        lbldefaultvaluemiddlename.setText("optional");

        lbldefaultvalueemail.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbldefaultvalueemail.setForeground(new java.awt.Color(204, 204, 204));
        lbldefaultvalueemail.setText("example@email.com");

        lbldefaultvaluezipcode.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbldefaultvaluezipcode.setForeground(new java.awt.Color(204, 204, 204));
        lbldefaultvaluezipcode.setText("1234 AB");

        lbldefaultvaluecode.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbldefaultvaluecode.setForeground(new java.awt.Color(204, 204, 204));
        lbldefaultvaluecode.setText("123A-456B-789C");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lbldefaultvalueemail)
                                .addGap(36, 36, 36)
                                .addComponent(lbldefaultvaluecode))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane4)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbl_departureFrom)
                                        .addComponent(lbl_material1)
                                        .addComponent(lbl_lableCode1)
                                        .addComponent(lbl_weightClass)
                                        .addComponent(lbl_color)
                                        .addComponent(lbl_brand1)
                                        .addComponent(lbl_otherDetails))
                                    .addGap(19, 19, 19)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(cmb_departureFrom, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cmb_weightClass, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cmb_color, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txt_brand, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txt_lableCode, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_material, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(38, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbldefaultvaluemiddlename)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbldefaultvaluezipcode)
                        .addGap(70, 70, 70))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_brand1)
                    .addComponent(txt_brand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_color)
                    .addComponent(cmb_color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_weightClass)
                    .addComponent(cmb_weightClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_departureFrom)
                    .addComponent(cmb_departureFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_material1)
                    .addComponent(txt_material, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_lableCode1)
                    .addComponent(txt_lableCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(lbl_otherDetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldefaultvaluemiddlename, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbldefaultvaluezipcode, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldefaultvalueemail, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbldefaultvaluecode, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Arial", 1, 23)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CONTACT DETAILS");

        jPanel4.setBackground(new java.awt.Color(255, 241, 234));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn_clear.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn_clear.setText("CLEAR ALL");
        btn_clear.setMinimumSize(new java.awt.Dimension(70, 25));
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        lbl_state.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_state.setText("State");

        lbl_middlename.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_middlename.setText("Middlename");

        txt_email.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_email.setText(" ");
        txt_email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_emailFocusLost(evt);
            }
        });
        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });
        txt_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_emailKeyPressed(evt);
            }
        });

        txt_phoneNumber.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_phoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_phoneNumberActionPerformed(evt);
            }
        });
        txt_phoneNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_phoneNumberKeyTyped(evt);
            }
        });

        txt_address.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_addressActionPerformed(evt);
            }
        });

        lbl_lastname.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_lastname.setText("Lastname");

        lbl_email.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_email.setText("Email");

        lbl_firstname.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_firstname.setText("Firstname");

        lbl_country.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_country.setText("Country ");

        lbl_phoneNumber.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_phoneNumber.setText("Phonenumber");

        txt_firstname.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_firstnameActionPerformed(evt);
            }
        });

        txt_lastName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_lastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_lastNameActionPerformed(evt);
            }
        });

        txt_state.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_state.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_stateActionPerformed(evt);
            }
        });

        txt_city.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_city.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cityActionPerformed(evt);
            }
        });

        txt_zipcode.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_zipcode.setText(" ");
        txt_zipcode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_zipcodeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_zipcodeFocusLost(evt);
            }
        });
        txt_zipcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_zipcodeActionPerformed(evt);
            }
        });
        txt_zipcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_zipcodeKeyPressed(evt);
            }
        });

        lbl_city.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_city.setText("City");

        lbl_zipCode.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_zipCode.setText("Zipcode");

        lbl_address.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_address.setText("Address");

        txt_middlename.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_middlename.setText(" ");
        txt_middlename.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_middlenameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_middlenameFocusLost(evt);
            }
        });
        txt_middlename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_middlenameActionPerformed(evt);
            }
        });
        txt_middlename.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_middlenameKeyPressed(evt);
            }
        });

        txt_country.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_country.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_countryActionPerformed(evt);
            }
        });

        checkPDF.setSelected(true);
        checkPDF.setText("Create PDF");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_lastname)
                    .addComponent(lbl_phoneNumber)
                    .addComponent(lbl_email)
                    .addComponent(lbl_country)
                    .addComponent(lbl_address)
                    .addComponent(lbl_city)
                    .addComponent(lbl_state)
                    .addComponent(lbl_zipCode)
                    .addComponent(lbl_firstname, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_middlename))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkPDF)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_firstname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_lastName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_phoneNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_country, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_address, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_city, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_state, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_zipcode, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_clear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txt_middlename, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(62, 62, 62))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(checkPDF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_firstname)
                    .addComponent(lbl_firstname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_middlename)
                    .addComponent(txt_middlename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_lastname)
                    .addComponent(txt_lastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_phoneNumber)
                    .addComponent(txt_phoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_email)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_country, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_country, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_address, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_city, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_state, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_state, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_zipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_zipcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel3.setFont(new java.awt.Font("Arial", 1, 23)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("REGISTER LOST LUGGAGE");

        btn_submit1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_submit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/check-icon.png"))); // NOI18N
        btn_submit1.setText("SUBMIT");
        btn_submit1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_submit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submit1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(174, 174, 174))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_submit1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(btn_submit1)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        Frame.getInstance().showPanel(new FoundLuggageOverview());
    }//GEN-LAST:event_backJButtonActionPerformed

    private void logoutJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutJButtonActionPerformed
        Frame.shutdown();
        FYSApp.logout();
    }//GEN-LAST:event_logoutJButtonActionPerformed

    private void txt_brandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_brandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_brandActionPerformed

    private void cmb_departureFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_departureFromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_departureFromActionPerformed

    private void txt_materialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_materialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_materialActionPerformed

    private void txt_lableCodeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_lableCodeFocusGained
        lbldefaultvaluecode.setText("");
    }//GEN-LAST:event_txt_lableCodeFocusGained

    private void txt_lableCodeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_lableCodeFocusLost
        lbldefaultvaluecode.setText("123A-456B-789C");
    }//GEN-LAST:event_txt_lableCodeFocusLost

    private void txt_lableCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_lableCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_lableCodeActionPerformed

    private void txt_lableCodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_lableCodeKeyPressed
        lbldefaultvaluecode.setText("");
    }//GEN-LAST:event_txt_lableCodeKeyPressed

    private void cmb_weightClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_weightClassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_weightClassActionPerformed

    private void cmb_colorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_colorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_colorActionPerformed

    private void txt_countryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_countryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_countryActionPerformed

    private void txt_middlenameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_middlenameKeyPressed
        lbldefaultvaluemiddlename.setText("");
    }//GEN-LAST:event_txt_middlenameKeyPressed

    private void txt_middlenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_middlenameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_middlenameActionPerformed

    private void txt_middlenameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_middlenameFocusLost
        lbldefaultvaluemiddlename.setText("optional");
    }//GEN-LAST:event_txt_middlenameFocusLost

    private void txt_middlenameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_middlenameFocusGained
        lbldefaultvaluemiddlename.setText("");
    }//GEN-LAST:event_txt_middlenameFocusGained

    private void txt_zipcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_zipcodeKeyPressed
        lbldefaultvaluezipcode.setText("");
    }//GEN-LAST:event_txt_zipcodeKeyPressed

    private void txt_zipcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_zipcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_zipcodeActionPerformed

    private void txt_zipcodeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_zipcodeFocusLost
        lbldefaultvaluezipcode.setText("1234 AB");
    }//GEN-LAST:event_txt_zipcodeFocusLost

    private void txt_zipcodeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_zipcodeFocusGained
        lbldefaultvaluezipcode.setText("");
    }//GEN-LAST:event_txt_zipcodeFocusGained

    private void txt_cityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cityActionPerformed

    private void txt_stateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_stateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_stateActionPerformed

    private void txt_lastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_lastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_lastNameActionPerformed

    private void txt_firstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_firstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_firstnameActionPerformed

    private void txt_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_addressActionPerformed

    private void txt_phoneNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_phoneNumberKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE)) {
            //  A sound.. lol
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txt_phoneNumberKeyTyped

    private void txt_phoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_phoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_phoneNumberActionPerformed

    private void txt_emailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_emailKeyPressed
        lbldefaultvalueemail.setText("");
    }//GEN-LAST:event_txt_emailKeyPressed

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        //
    }//GEN-LAST:event_txt_emailActionPerformed

    private void txt_emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_emailFocusLost
        lbldefaultvalueemail.setText("example@email.com");
    }//GEN-LAST:event_txt_emailFocusLost

    private void txt_emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_emailFocusGained
        lbldefaultvalueemail.setText("");
    }//GEN-LAST:event_txt_emailFocusGained

    private void btn_submit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submit1ActionPerformed

        //  Create client
        String firstName = txt_firstname.getText();
        String middleName = txt_middlename.getText();
        String lastName = txt_lastName.getText();

        String phone = txt_phoneNumber.getText();
        String email = txt_email.getText();

        String country = txt_country.getText();
        String address = txt_address.getText();
        String city = txt_city.getText();
        String state = txt_state.getText();
        String zipCode = txt_zipcode.getText();

        //        if (areAllNotEmpty(firstName, middleName, lastName, phone, email,
        //                country, address, city, state, zipCode)) {
        //            JOptionPane.showMessageDialog(null, "No data entered");
        //        }
        //  Calling client constructor from the client class
        Client newClient = new Client(firstName, middleName, lastName, phone,
                email, country, address, city, state, zipCode);

        //  store user input in variables
        String brand = txt_brand.getText();
        String color
                = String.valueOf(cmb_color.getSelectedItem());
        String weightClass
                = String.valueOf(cmb_weightClass.getSelectedItem());
        String departureFrom
                = String.valueOf(cmb_departureFrom.getSelectedItem());
        String material = txt_material.getText();
        String lableCode = txt_email.getText();
        String otherDetails = txt_otherDetails.getText();
        String status = "Lost";
        String whenFound = "";
        String foundAt = "";
        
        //  Create lost luggage item with user input
        Luggage luggage = new Luggage(brand, lableCode, material,
                otherDetails, status, color, weightClass, whenFound, foundAt,
                departureFrom);
           
        if(checkPDF.isSelected()){
            FYSApp.getInstance().getPDFGenerator().getReceiptPDF(luggage, newClient);
        }
        
        try {
            if (updateMode > 1) {
                FYSApp.getLuggageManager().updateLuggage(luggage, luggageid);
            } else {
                //  Show user succes message
                JOptionPane.showMessageDialog(null, "Information is saved");
                //  If this is not the case, then we call the addLuggage Query +
                //  the add client luggage
                FYSApp.getClientManager().addClient(newClient);
                int id = FYSApp.getClientManager().getClientid();
                FYSApp.getLuggageManager().addLostLuggage(luggage, id);
            }

            Frame.getInstance().showPanel(new LostLuggageOverview());

        } catch (HeadlessException | ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btn_submit1ActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        //clear all the fields
        txt_brand.setText("");
        cmb_color.setSelectedIndex(0);
        cmb_weightClass.setSelectedIndex(0);

    }//GEN-LAST:event_btn_clearActionPerformed

    public static void setText(Luggage luggage) {
        txt_brand.setText(luggage.getBrand());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_submit1;
    private java.awt.Canvas canvas1;
    private javax.swing.JCheckBox checkPDF;
    private static javax.swing.JComboBox cmb_color;
    private static javax.swing.JComboBox cmb_departureFrom;
    private static javax.swing.JComboBox cmb_weightClass;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lbl_address;
    private javax.swing.JLabel lbl_brand1;
    private javax.swing.JLabel lbl_city;
    private javax.swing.JLabel lbl_color;
    private javax.swing.JLabel lbl_country;
    private javax.swing.JLabel lbl_departureFrom;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_firstname;
    private javax.swing.JLabel lbl_lableCode1;
    private javax.swing.JLabel lbl_lastname;
    private javax.swing.JLabel lbl_material1;
    private javax.swing.JLabel lbl_middlename;
    private javax.swing.JLabel lbl_otherDetails;
    private javax.swing.JLabel lbl_phoneNumber;
    private javax.swing.JLabel lbl_state;
    private javax.swing.JLabel lbl_weightClass;
    private javax.swing.JLabel lbl_zipCode;
    private javax.swing.JLabel lbldefaultvaluecode;
    private javax.swing.JLabel lbldefaultvalueemail;
    private javax.swing.JLabel lbldefaultvaluemiddlename;
    private javax.swing.JLabel lbldefaultvaluezipcode;
    private javax.swing.JButton logoutJButton;
    private javax.swing.JTextField txt_address;
    private static javax.swing.JTextField txt_brand;
    private javax.swing.JTextField txt_city;
    private javax.swing.JTextField txt_country;
    private static javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_firstname;
    private static javax.swing.JTextField txt_lableCode;
    private javax.swing.JTextField txt_lastName;
    private static javax.swing.JTextField txt_material;
    private static javax.swing.JTextField txt_middlename;
    private static javax.swing.JTextArea txt_otherDetails;
    private javax.swing.JTextField txt_phoneNumber;
    private javax.swing.JTextField txt_state;
    private static javax.swing.JTextField txt_zipcode;
    // End of variables declaration//GEN-END:variables
}
