/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view.admin;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import main.FYSApp;
import main.Frame;
import model.Client;
import model.Luggage;
import view.employee.RegisterLostLuggage;

/**
 *
 * @author Gebruiker
 */
public class EditLostLuggage extends javax.swing.JPanel {

    private static int luggageid;
    private static String status;
    
    /**
     * Creates new form EditLostLuggage
     */
    public EditLostLuggage() {
        initComponents();
        setLoggedInAs();
        
    }
    
    public static void setLuggageId(int id) {
        EditLostLuggage.luggageid = id;
    }
    
    public static void setStatus(String status) {
        EditLostLuggage.status = status;
    }
    
    public static void setText(Luggage luggage) {
        txt_brand.setText(luggage.getBrand());
        txt_lableCode.setText(luggage.getLableCode());
        txt_material.setText(luggage.getMaterial());
        txt_otherDetails.setText(luggage.getOtherDetails());
        cmb_color.setSelectedItem(luggage.getColor());
        cmb_departureFrom.setSelectedItem(luggage.getDepartureFrom());
        cmb_weightClass.setSelectedItem(luggage.getWeightClass());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_leftTitle = new javax.swing.JLabel();
        lbl_brand = new javax.swing.JLabel();
        lbl_color = new javax.swing.JLabel();
        lbl_weightClass = new javax.swing.JLabel();
        lbl_departureFrom = new javax.swing.JLabel();
        lbl_material = new javax.swing.JLabel();
        lbl_lableCode = new javax.swing.JLabel();
        lbl_otherDetails = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txt_otherDetails = new javax.swing.JTextArea();
        submitJButton = new javax.swing.JButton();
        clearJButton = new javax.swing.JButton();
        txt_brand = new javax.swing.JTextField();
        cmb_color = new javax.swing.JComboBox();
        cmb_weightClass = new javax.swing.JComboBox();
        cmb_departureFrom = new javax.swing.JComboBox();
        txt_material = new javax.swing.JTextField();
        txt_lableCode = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        logoutJButton = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        lbl_loadingMessage = new javax.swing.JLabel();
        loggedInAs = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_leftTitle.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lbl_leftTitle.setForeground(new java.awt.Color(255, 255, 255));
        lbl_leftTitle.setText("Edit Lost Luggage");
        add(lbl_leftTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 360, 30));

        lbl_brand.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lbl_brand.setForeground(new java.awt.Color(255, 255, 255));
        lbl_brand.setText("Brand:");
        add(lbl_brand, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));

        lbl_color.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lbl_color.setForeground(new java.awt.Color(255, 255, 255));
        lbl_color.setText("Color:");
        add(lbl_color, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        lbl_weightClass.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lbl_weightClass.setForeground(new java.awt.Color(255, 255, 255));
        lbl_weightClass.setText("Weight class:");
        add(lbl_weightClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        lbl_departureFrom.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lbl_departureFrom.setForeground(new java.awt.Color(255, 255, 255));
        lbl_departureFrom.setText("Departure from:");
        add(lbl_departureFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, -1, -1));

        lbl_material.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lbl_material.setForeground(new java.awt.Color(255, 255, 255));
        lbl_material.setText("Material:");
        add(lbl_material, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, -1, -1));

        lbl_lableCode.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lbl_lableCode.setForeground(new java.awt.Color(255, 255, 255));
        lbl_lableCode.setText("lable code");
        add(lbl_lableCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, -1, -1));

        lbl_otherDetails.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lbl_otherDetails.setForeground(new java.awt.Color(255, 255, 255));
        lbl_otherDetails.setText("Other details:");
        add(lbl_otherDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, -1, -1));

        txt_otherDetails.setColumns(20);
        txt_otherDetails.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txt_otherDetails.setRows(5);
        jScrollPane4.setViewportView(txt_otherDetails);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 340, 60));

        submitJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/check-icon.png"))); // NOI18N
        submitJButton.setText("SUBMIT");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });
        add(submitJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, 130, 30));

        clearJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cancel-icon.png"))); // NOI18N
        clearJButton.setText("CANCEL");
        clearJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearJButtonActionPerformed(evt);
            }
        });
        add(clearJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 450, 130, 30));

        txt_brand.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txt_brand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_brandActionPerformed(evt);
            }
        });
        add(txt_brand, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 160, -1));

        cmb_color.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmb_color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_colorActionPerformed(evt);
            }
        });
        add(cmb_color, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 160, -1));

        cmb_weightClass.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmb_weightClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_weightClassActionPerformed(evt);
            }
        });
        add(cmb_weightClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 160, -1));

        cmb_departureFrom.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmb_departureFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_departureFromActionPerformed(evt);
            }
        });
        add(cmb_departureFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 160, -1));

        txt_material.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txt_material.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_materialActionPerformed(evt);
            }
        });
        add(txt_material, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 160, -1));

        txt_lableCode.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txt_lableCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_lableCodeActionPerformed(evt);
            }
        });
        add(txt_lableCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 160, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Currently logged in as: ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        logoutJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout-icon.png"))); // NOI18N
        logoutJButton.setText("Logout");
        logoutJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutJButtonActionPerformed(evt);
            }
        });
        add(logoutJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 20, 100, 30));
        add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, 340, 20));

        lbl_loadingMessage.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_loadingMessage.setForeground(new java.awt.Color(255, 255, 255));
        lbl_loadingMessage.setText("Loading message..");
        add(lbl_loadingMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 500, -1, 10));

        loggedInAs.setForeground(new java.awt.Color(255, 255, 255));
        loggedInAs.setText("jLabel2");
        add(loggedInAs, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Corendon-background.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setMaximumSize(new java.awt.Dimension(1024, 600));
        jLabel3.setMinimumSize(new java.awt.Dimension(1024, 600));
        jLabel3.setPreferredSize(new java.awt.Dimension(1024, 600));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed

        //  store user input in variables
        String brand = txt_brand.getText();
        String color
        = String.valueOf(cmb_color.getSelectedItem());
        String weightClass
        = String.valueOf(cmb_weightClass.getSelectedItem());
        String departureFrom
        = String.valueOf(cmb_departureFrom.getSelectedItem());
        String material = txt_material.getText();
        String lableCode = txt_lableCode.getText();
        String otherDetails = txt_otherDetails.getText();
        String whenFound = "";
        String foundAt = "";
        String statuss = status;

        //  Create lost luggage item with user input
        Luggage luggage = new Luggage(brand, lableCode, material,
            otherDetails, statuss, color, weightClass, whenFound, foundAt,
            departureFrom);

        //  COMMENT
            FYSApp.getLuggageManager().updateLuggage(luggage, luggageid); // werkt pas na chris zijn push.

        try {
            //  COMMENT

            Frame.getInstance().showPanel(new AdminLuggageLost());
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(EditLostLuggage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_submitJButtonActionPerformed

    private void clearJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearJButtonActionPerformed
        try {
            Frame.getInstance().showPanel(new AdminLuggageLost());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(EditLostLuggage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(EditLostLuggage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_clearJButtonActionPerformed

    private void txt_brandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_brandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_brandActionPerformed

    private void cmb_colorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_colorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_colorActionPerformed

    private void cmb_weightClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_weightClassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_weightClassActionPerformed

    private void cmb_departureFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_departureFromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_departureFromActionPerformed

    private void txt_materialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_materialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_materialActionPerformed

    private void txt_lableCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_lableCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_lableCodeActionPerformed

    private void logoutJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutJButtonActionPerformed
        Frame.shutdown();
        FYSApp.logout();
    }//GEN-LAST:event_logoutJButtonActionPerformed

    
    private void setLoggedInAs() {
        String userName = FYSApp.getUserManager().getUserName();
        System.out.println(userName);
        loggedInAs.setText(userName);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearJButton;
    private static javax.swing.JComboBox cmb_color;
    private static javax.swing.JComboBox cmb_departureFrom;
    private static javax.swing.JComboBox cmb_weightClass;
    private javax.swing.JLabel jLabel1;
    private static javax.swing.JLabel jLabel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lbl_brand;
    private javax.swing.JLabel lbl_color;
    private javax.swing.JLabel lbl_departureFrom;
    private javax.swing.JLabel lbl_lableCode;
    private javax.swing.JLabel lbl_leftTitle;
    private javax.swing.JLabel lbl_loadingMessage;
    private javax.swing.JLabel lbl_material;
    private javax.swing.JLabel lbl_otherDetails;
    private javax.swing.JLabel lbl_weightClass;
    private javax.swing.JLabel loggedInAs;
    private javax.swing.JButton logoutJButton;
    private javax.swing.JButton submitJButton;
    private static javax.swing.JTextField txt_brand;
    private static javax.swing.JTextField txt_lableCode;
    private static javax.swing.JTextField txt_material;
    private static javax.swing.JTextArea txt_otherDetails;
    // End of variables declaration//GEN-END:variables
}
