/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.admin;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import main.FYSApp;
import main.Frame;
import model.Luggage;

/**
 *
 * @author Gebruiker
 */
public class EditLuggage extends javax.swing.JPanel {

    private static int luggageid;
    private static String status;

    /**
     * Creates new form EditLostLuggage
     */
    public EditLuggage() {
        initComponents();
        setLoggedInAs();

        cmb_color.addItem("other..");
        cmb_color.addItem("red");
        cmb_color.addItem("blue");
        cmb_color.addItem("cyan");
        cmb_color.addItem("yellow");
        cmb_color.addItem("pink");
        cmb_color.addItem("magenta");
        cmb_color.addItem("green");
        cmb_color.addItem("black");
        cmb_color.addItem("white");
        cmb_color.addItem("orange");
        cmb_color.addItem("grey");
        cmb_color.addItem("brown");

        cmb_weightClass.addItem("other..");
        cmb_weightClass.addItem("0kg - 5kg");
        cmb_weightClass.addItem("5kg - 10kg");
        cmb_weightClass.addItem("10kg - 15kg");
        cmb_weightClass.addItem("15kg - 20kg");
        cmb_weightClass.addItem("20kg+");

        setAirports();

    }

    public static void setLuggageId(int id) {
        EditLuggage.luggageid = id;
    }

    public static void setStatus(String status) {
        EditLuggage.status = status;
    }

    public static void setText(Luggage luggage) {
        //  Fill GUI components with data from luggage object
        txt_brand.setText(luggage.getBrand());
        txt_lableCode.setText(luggage.getLableCode());
        txt_material.setText(luggage.getMaterial());
        txt_otherDetails.setText(luggage.getOtherDetails());
        cmb_color.setSelectedItem(luggage.getColor());
        cmb_departureFrom.setSelectedItem(luggage.getDepartureFrom());
        cmb_weightClass.setSelectedItem(luggage.getWeightClass());
        cmb_foundAt.setSelectedItem(luggage.getFoundAt());
        txt_whenFound.setText(luggage.getWhenFound());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_editLuggageTitle = new javax.swing.JLabel();
        lbl_brand = new javax.swing.JLabel();
        lbl_color = new javax.swing.JLabel();
        lbl_weightClass = new javax.swing.JLabel();
        lbl_departureFrom = new javax.swing.JLabel();
        lbl_material = new javax.swing.JLabel();
        lbl_lableCode = new javax.swing.JLabel();
        lbl_otherDetails = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txt_otherDetails = new javax.swing.JTextArea();
        submitJButton = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        txt_brand = new javax.swing.JTextField();
        cmb_color = new javax.swing.JComboBox();
        cmb_weightClass = new javax.swing.JComboBox();
        cmb_foundAt = new javax.swing.JComboBox();
        txt_material = new javax.swing.JTextField();
        txt_lableCode = new javax.swing.JTextField();
        lbl_loggedInAs1 = new javax.swing.JLabel();
        logoutJButton = new javax.swing.JButton();
        lbl_loggedInAs2 = new javax.swing.JLabel();
        lbl_brand1 = new javax.swing.JLabel();
        lbl_brand2 = new javax.swing.JLabel();
        txt_whenFound = new javax.swing.JTextField();
        cmb_departureFrom = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_editLuggageTitle.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lbl_editLuggageTitle.setForeground(new java.awt.Color(255, 255, 255));
        lbl_editLuggageTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/edit-icon.png"))); // NOI18N
        lbl_editLuggageTitle.setText("   Edit Luggage");
        add(lbl_editLuggageTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 360, 30));

        lbl_brand.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lbl_brand.setForeground(new java.awt.Color(255, 255, 255));
        lbl_brand.setText("When found:");
        add(lbl_brand, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, -1, -1));

        lbl_color.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lbl_color.setForeground(new java.awt.Color(255, 255, 255));
        lbl_color.setText("Color:");
        add(lbl_color, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, -1, -1));

        lbl_weightClass.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lbl_weightClass.setForeground(new java.awt.Color(255, 255, 255));
        lbl_weightClass.setText("Weight class:");
        add(lbl_weightClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, -1, -1));

        lbl_departureFrom.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lbl_departureFrom.setForeground(new java.awt.Color(255, 255, 255));
        lbl_departureFrom.setText("Departure from:");
        add(lbl_departureFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, -1, -1));

        lbl_material.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lbl_material.setForeground(new java.awt.Color(255, 255, 255));
        lbl_material.setText("Material:");
        add(lbl_material, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, -1, -1));

        lbl_lableCode.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lbl_lableCode.setForeground(new java.awt.Color(255, 255, 255));
        lbl_lableCode.setText("Lable code:");
        add(lbl_lableCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, -1, -1));

        lbl_otherDetails.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lbl_otherDetails.setForeground(new java.awt.Color(255, 255, 255));
        lbl_otherDetails.setText("Other details:");
        add(lbl_otherDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, -1, -1));

        txt_otherDetails.setColumns(20);
        txt_otherDetails.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txt_otherDetails.setRows(5);
        jScrollPane4.setViewportView(txt_otherDetails);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 450, 340, 60));

        submitJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/check-icon.png"))); // NOI18N
        submitJButton.setText("SUBMIT");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });
        add(submitJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 520, 130, 30));

        btn_cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cancel-icon.png"))); // NOI18N
        btn_cancel.setText("CANCEL");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });
        add(btn_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 520, 130, 30));

        txt_brand.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txt_brand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_brandActionPerformed(evt);
            }
        });
        add(txt_brand, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 160, -1));

        cmb_color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_colorActionPerformed(evt);
            }
        });
        add(cmb_color, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 160, -1));

        cmb_weightClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_weightClassActionPerformed(evt);
            }
        });
        add(cmb_weightClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, 160, -1));

        cmb_foundAt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_foundAtActionPerformed(evt);
            }
        });
        add(cmb_foundAt, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, 160, -1));

        txt_material.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txt_material.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_materialActionPerformed(evt);
            }
        });
        add(txt_material, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, 160, -1));

        txt_lableCode.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txt_lableCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_lableCodeActionPerformed(evt);
            }
        });
        add(txt_lableCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, 160, -1));

        lbl_loggedInAs1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_loggedInAs1.setText("Currently logged in as: ");
        add(lbl_loggedInAs1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        logoutJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout-icon.png"))); // NOI18N
        logoutJButton.setText("Logout");
        logoutJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutJButtonActionPerformed(evt);
            }
        });
        add(logoutJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(917, 20, -1, 30));

        lbl_loggedInAs2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_loggedInAs2.setText("[username]");
        add(lbl_loggedInAs2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        lbl_brand1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lbl_brand1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_brand1.setText("Brand:");
        add(lbl_brand1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, -1, -1));

        lbl_brand2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lbl_brand2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_brand2.setText("Found at:");
        add(lbl_brand2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, -1, -1));

        txt_whenFound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_whenFoundActionPerformed(evt);
            }
        });
        add(txt_whenFound, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 380, 160, -1));

        cmb_departureFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_departureFromActionPerformed(evt);
            }
        });
        add(cmb_departureFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 160, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Corendon-background.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setMaximumSize(new java.awt.Dimension(1024, 600));
        jLabel3.setMinimumSize(new java.awt.Dimension(1024, 600));
        jLabel3.setPreferredSize(new java.awt.Dimension(1024, 600));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed

        //  store user input in variables
        String brand = txt_brand.getText();
        String color
                = String.valueOf(cmb_color.getSelectedItem());
        String weightClass
                = String.valueOf(cmb_weightClass.getSelectedItem());
        String departureFrom
                = String.valueOf(cmb_departureFrom.getSelectedItem());
        String material = txt_material.getText();
        String lableCode = txt_lableCode.getText();
        String otherDetails = txt_otherDetails.getText();
        String whenFound = txt_whenFound.getText();
        String foundAt = (String) cmb_foundAt.getSelectedItem();

        //  Create lost luggage item with user input
        Luggage luggage = new Luggage(brand, lableCode, material,
                otherDetails, status, color, weightClass, whenFound, foundAt,
                departureFrom);

        //  Call method to update the luggage, give luggage object and
        //  current luggageid
        FYSApp.getLuggageManager().updateLuggage(luggage, luggageid);

        try {
            //  If the status was lost and user submits, you get redirected to
            //  the AdminLuggageLost panel
            if (status.equalsIgnoreCase("lost")) {
                Frame.getInstance().showPanel(new AdminLuggageLost());
            } else {
                Frame.getInstance().showPanel(new AdminLuggageFound());
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(EditLuggage.class.getName())
                    .log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_submitJButtonActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        try {
            if (status.equalsIgnoreCase("lost")) {
                Frame.getInstance().showPanel(new AdminLuggageLost());
            } else {
                Frame.getInstance().showPanel(new AdminLuggageFound());
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(EditLuggage.class.getName())
                    .log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void txt_brandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_brandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_brandActionPerformed

    private void cmb_colorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_colorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_colorActionPerformed

    private void cmb_weightClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_weightClassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_weightClassActionPerformed

    private void cmb_foundAtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_foundAtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_foundAtActionPerformed

    private void txt_materialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_materialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_materialActionPerformed

    private void txt_lableCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_lableCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_lableCodeActionPerformed

    private void logoutJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutJButtonActionPerformed
        FYSApp.logout();
        Frame.shutdown();
    }//GEN-LAST:event_logoutJButtonActionPerformed

    private void txt_whenFoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_whenFoundActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_whenFoundActionPerformed

    private void cmb_departureFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_departureFromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_departureFromActionPerformed

    private void setLoggedInAs() {
        //  Call getter from userManager class and store in variable
        String userName = FYSApp.getUserManager().getUserName();
        lbl_loggedInAs2.setText(userName);
    }

    public static void setAirports() {
        ArrayList<String> airtportlist = FYSApp.getQueryManager().getAirports();
        cmb_foundAt.addItem("other..");
        for (String airport : airtportlist) {
            cmb_foundAt.addItem(airport);
            cmb_departureFrom.addItem(airport);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private static javax.swing.JComboBox cmb_color;
    private static javax.swing.JComboBox cmb_departureFrom;
    private static javax.swing.JComboBox cmb_foundAt;
    private static javax.swing.JComboBox cmb_weightClass;
    private static javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lbl_brand;
    private javax.swing.JLabel lbl_brand1;
    private javax.swing.JLabel lbl_brand2;
    private javax.swing.JLabel lbl_color;
    private javax.swing.JLabel lbl_departureFrom;
    private javax.swing.JLabel lbl_editLuggageTitle;
    private javax.swing.JLabel lbl_lableCode;
    private javax.swing.JLabel lbl_loggedInAs1;
    private javax.swing.JLabel lbl_loggedInAs2;
    private javax.swing.JLabel lbl_material;
    private javax.swing.JLabel lbl_otherDetails;
    private javax.swing.JLabel lbl_weightClass;
    private javax.swing.JButton logoutJButton;
    private javax.swing.JButton submitJButton;
    private static javax.swing.JTextField txt_brand;
    private static javax.swing.JTextField txt_lableCode;
    private static javax.swing.JTextField txt_material;
    private static javax.swing.JTextArea txt_otherDetails;
    private static javax.swing.JTextField txt_whenFound;
    // End of variables declaration//GEN-END:variables
}
